# Change these first
owner: zeroboard-dev # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Dataseed website
    url: https://www.dataseed.jp
    icon: https://test.dataseed.jp/favicon.ico
  - name: Dataseed application
    url: https://test.dataseed.jp
    icon: https://test.dataseed.jp/favicon.ico
  - name: Dataseed API
    url: https://api.dataseed.jp/docs
    icon: https://test.dataseed.jp/favicon.ico
  - name: Dataseed blog
    url: https://www.dataseed.jp/news
    icon: https://test.dataseed.jp/favicon.ico
  - name: Dataseed ESG AI
    url: https://chat.dataseed.jp
    icon: https://chat.dataseed.jp/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.dataseed.jp
  # baseUrl: /status-page
  logoUrl: https://www.dataseed.jp/_next/image?url=%2Fglobal%2FDataseed_logo.png&w=640&q=75
  name: Dataseed
  introTitle: "はじめてのESG経営から、100年先も続く企業へ"
  introMessage: "Dataseedは、ESG導入からデータ収集・分析、 経営判断への活用までステークホルダーが納得する 長期的な企業価値育成をサポートします。"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
