# Change these first
owner: zeroboard-dev # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  # Production
  - name: Production Frontend
    url: https://dataseed.zeroboard.jp
    icon: https://dataseed.zeroboard.jp/favicon.ico
  - name: Production API
    url: https://prod-api.dataseed.zeroboard.jp/health
    icon: https://dataseed.zeroboard.jp/favicon.ico
  # Staging
  - name: Staging Frontend
    url: https://stg.dataseed.zeroboard-dev.jp
    icon: https://stg.dataseed.zeroboard-dev.jp/favicon.ico
  - name: Staging API
    url: https://stg-api.dataseed.zeroboard-dev.jp/health
    icon: https://stg.dataseed.zeroboard-dev.jp/favicon.ico
  # Dev
  - name: Dev Frontend
    url: https://dev.dataseed.zeroboard-dev.jp
    icon: https://dev.dataseed.zeroboard-dev.jp/favicon.ico
  - name: Dev API
    url: https://dev-api.dataseed.zeroboard-dev.jp/health
    icon: https://dev.dataseed.zeroboard-dev.jp/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.dataseed.jp
  # baseUrl: /status-page
  logoUrl: https://dataseed.zeroboard.jp/favicon.ico
  name: Dataseed Status
  introTitle: "Dataseed System Status"
  introMessage: "Real-time monitoring of Dataseed services across Development, Staging, and Production environments."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
